config/routes.rb
Rails.application.routes.draw do

  resources :images
  root :to => 'home#index'
  get '/about' => "home#about", as: :about
  get 'homes/new' => "home#new"
  post 'homes/create' => "home#create"
  get '/admin' => "home#admin"

  resources :scores
  post '/scores/search' => 'scores#score_search'

  resources :games
  post '/ballot.json' => 'games#ballot'
  get '/creating_a_game_for_each_team/:team_name' => 'gemes#creating_a_game_for_each_team', as: :creating_a_game_for_each_team
  resources :users

  get '/sign_up' => 'users#new', as: :sign_up
  get '/sign_in' => 'users#sign_in', as: :sign_in
  post '/login' => 'users#login', as: :login
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :banner_url, ImageUploader
  has_many :game_scores

  def join_people
    self.game_scores.count
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  def creating_a_game_for_each_team
    @games = Game.where(create_team: params[:team_name])
    render 'games/index'
  end

  # GET /games/1
  # GET /games/1.json
  def show
    game_id =  params["id"].to_i
    @game_score = Game.find_by(id: game_id).game_scores.map(&:score).sort_by(&:score).reverse.first(3)
  end

  # GET /games/new
  def new
    admin? ? @game = Game.new : (redirect_to :root)
  end

  # GET /games/1/edit
  def edit
    admin? ? nil : (redirect_to :root )
  end

  # POST /games
  # POST /games.json
  def create
    if admin?
      @game = Game.new(game_params)

      respond_to do |format|
        if @game.save
          format.html { redirect_to @game, notice: 'Game was successfully created.' }
          format.json { render :show, status: :created, location: @game }
        else
          format.html { render :new }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if admin?
      respond_to do |format|
        if @game.update(game_params)
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { render :show, status: :ok, location: @game }
        else
          format.html { render :edit }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    if admin?
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def ballot
    unless session[:ballot]
      game = Game.find_by(id: params["form_ballot"].to_i)
      game.update(like: game.like + 1)
      session[:ballot] = true
      personal = {'status' => 'Successfully'}; render :json => personal
    else
      personal = {'status' => 'Already'}; render :json => personal
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:banner_url, :title, :create_team, :bio, :like)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message.to_s %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :create_team %>
    <%= f.text_field :create_team, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= f.label :banner_url %>
    <%= f.file_field :banner_url %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="body">
  <h1>Editing Game</h1>

  <%= render 'form', game: @game %>

  <%= link_to 'Show', @game %> |
  <%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>

  <h1>Games</h1>

  <%= (link_to 'New Game', new_game_path) if admin? %>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Creater</th>
        <th>Bio</th>
        <th>Join</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= link_to game.title , game %></td>
          <td><%= game.create_team %></td>
          <td><%= game.bio %></td>
          <td><%= game.join_people %></td>
          <% if admin? %>
            <td><%= link_to 'Edit', edit_game_path(game) %></td>
            <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/games/new.html.erb
<div class="body">
  <h1>New Game</h1>
  <%= render 'form', game: @game %>
  <%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<div class="slide row">
  <div class="col-lg-12" style="padding: 0;">
    <%= image_tag @game.banner_url.thumb.url, :width => '100%' %>
  </div>
</div>

<div class="body game-show">
  <p id="notice"><%= notice %></p>

  <p>
    <h1><%= @game.title %></h1>
  </p>

  <p>
    <h2>【作成者】</h2>
    <h3><%= @game.create_team %></h3>
  </p>

  <p>
    <h2>【ゲーム説明】</h2>
    <h3><%= simple_format(@game.bio) %></h3>
  </p>

  <p>
    <h2>【いいね数】</h2>
    <h3><%= @game.like %></h3>
  </p>

  <p>
    <h2>【ハイスコアトップ３】</h2>
    <% @game_score.each_with_index do |score, index| %>
      <div class="score-ranking">
        <h1><%= "#{index + 1}位 #{score.name}さん" %></h1>
        <h2><%= score.score %>点</h2>
      </div>
    <% end %>
    <h3 style="font-weight: bold;"><%= link_to "すべてのスコアを見る", score_path %></h3>
  </p>

</div>