config/routes.rb
Rails.application.routes.draw do

  resources :images
  root :to => 'home#index'
  get '/about' => "home#about", as: :about
  get 'homes/new' => "home#new"
  post 'homes/create' => "home#create"
  get '/admin' => "home#admin"

  resources :scores
  post '/scores/search' => 'scores#score_search'

  resources :games
  post '/ballot.json' => 'games#ballot'
  get '/creating_a_game_for_each_team/:team_name' => 'gemes#creating_a_game_for_each_team', as: :creating_a_game_for_each_team
  resources :users

  get '/sign_up' => 'users#new', as: :sign_up
  get '/sign_in' => 'users#sign_in', as: :sign_in
  post '/login' => 'users#login', as: :login
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    if admin?
      @image = Image.new
    else
      redirect_to :root
    end
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    if admin?
      debug @image = Image.new(image_params)
      respond_to do |format|
        if @image.save
          redirect_to :new_image
        else
          format.html { render :new }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    if admin?
      @image.destroy
      respond_to do |format|
        format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message.to_s %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>

  <h1>Images</h1>

  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @images.each do |image| %>
        <tr style="margin: 30px;">
          <td><%= image_tag image.image, :width => '100%' %></td>
          <% if admin? %>
            <td><%= link_to 'Edit', edit_image_path(image) %></td>
            <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/images/new.html.erb
<div class="body">
  <h1>New Image</h1>

  <%= render 'form', image: @image %>

  <%= link_to 'Back', images_path %>
</div>

app/views/images/show.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag @image.image %>
  </p>
</div>